KEY_EXAMPLE_ID = 'example_id'
KEY_CATEGORY = 'nameusage'
KEY_LATITUDE = 'latitude'
KEY_LONGITUDE = 'longitude'
KEY_ELEVATION = 'elevation'
KEY_DATE ='date'
KEY_AVG_TEMP = 'avg_temp'
KEY_MAX_TEMP = 'max_temp'
KEY_MIN_TEMP = 'min_temp'
KEY_PRCP = 'precipitation'
KEY_DAYLIGHT = 'daylight'
KEY_S2_TOKENS = 's2_tokens'
KEY_ECO_BIOME = 'eco_biome'
KEY_ECO_REALM = 'eco_realm'
KEY_ECO_NUM = 'eco_num'

KEY_ECO_REGION = 'eco_region' # Cross-Column between Biome and Num
